### PR TITLE
Added tests for deleting embeddings

### PR DESCRIPTION
**Pull request by kyleburgess2025**

### CODE REVIEW

**Comment by langdonholmes** [comment]
What happens if the tests are run out of order? It kind of looks like `test_delete()` is meant to follow the tests that create the `test_chunk` resources. We can't assume sequence when working with pytest. In practice, I don't think this will have any effect, as the response code should be the same in both cases (either the resource has been deleted or the resource does not exist).

In any case, I think a better approach would be to create a pytest fixture that creates a temporary chunk in the DB, this fixture would be a dependency of `test_delete()`. The `test_delete()` function would call the appropriate endpoint, then query the database to see if the chunk has been deleted. If the chunk has been deleted, the test passes.

Sidenote that the other tests in this repo are not great. This is partially because a lot of the responses depend on deep learning stuff, and the exact response is not deterministic or changes frequently as we iterate on our models. There is still a lot of improvements we can make though, and I think we can do better than asserting a status code in most cases. I'm sorry for holding you to a higher standard, but I think this is a good time to start improving on our test suite.

Another sidenote, I think the response should be 202 instead of 200. [https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE). I missed this in the last review, but it should be simple enough to add a `status_code=202` in `embeddings.py`.

**Comment by kyleburgess2025** [comment]
@langdonholmes side note - should I change the `delete/embedding` route to a DELETE method instead of a POST method?

**Comment by langdonholmes** [comment]
> @langdonholmes side note - should I change the `delete/embedding` route to a DELETE method instead of a POST method?

Good thought. I wonder if PUT is actually the more appropriate verb? I think the API calls are structured such that we "update" a page's list of chunks in the vector-store. Technically, each chunk is a row in the DB, but pages are the operational unit from the perspective of the API endpoint.

I think DELETE is used for deleting specific item/s, and can return a 404 if the item/s to be deleted are not found. This doesn't make a lot of sense in our case, since we don't specify which resources should be deleted in the API call -- we specify the list of resources that we want to preserve.

Anyway, I have no strong opinions here, so I'll leave it up to you. [Reference for CRUD operations with HTTP methods](https://www.restapitutorial.com/lessons/httpmethods.html).

**Review by langdonholmes — APPROVED** [review]
This looks great. Thanks for your work here, Kyle.

Looking forward to further contributions from you!

**Pull request merged**
